openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /baccarat:
    get:
      summary: Get Baccarat
      operationId: get_baccarat_baccarat_get
      parameters:
        - name: num_records
          in: query
          required: false
          schema:
            type: integer
            maximum: 100
            default: 1
            title: Num Records
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError